steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcs-backup-service:$COMMIT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcs-backup-service:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google-appengine/exec-wrapper'
  args:
  - '-i'
  - 'gcr.io/$PROJECT_ID/gcs-backup-service:$COMMIT_SHA'
  - '--'
  - 'gcloud'
  - 'run'
  - 'deploy'
  - 'gcs-backup-service'
  - '--image'
  - 'gcr.io/$PROJECT_ID/gcs-backup-service:$COMMIT_SHA'
  - '--region'
  - 'us-central1' # TODO: Change to your preferred region
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' # Or configure for authenticated access
  

images:
- 'gcr.io/$PROJECT_ID/gcs-backup-service:$COMMIT_SHA'
